version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - project-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - MONGO_URI=mongodb://mongo:27017/node-api
    depends_on:
      - mongo
    networks:
      - project-network

  mongo:
    image: mongo:8.0
    container_name: mongo
    ports:
      - "27017:27017"  
    environment:
      - MONGO_URI=mongodb://mongo:27017/node-api  
    volumes:
      - mongo-data:/data/db
    networks:
      - project-network

volumes:
  mongo-data:

networks:
  project-network:
    driver: bridge
